server:
  port: 9001

spring:
  application:
    name: dearoffer-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://45.40.205.130:3306/offer?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: 129.28.154.216
  rabbitmq:
    host: 129.28.154.216
  cloud:
    refresh:
      refreshable: none

redis:
  keys:
    register_code_fix: 'register:code:phone_'

message:
  register:
    effectiveTime: 2

eureka:
  client:
    service‐url:
      defaultZone: http://129.28.154.216:8686/eureka
  instance:
    prefer‐ip‐address: true
