server:
  port: 9002

spring:
  application:
    name: dearoffer-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.230.128:3306/offer?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  redis:
    host: 192.168.230.128
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8686/eureka
  instance:
    prefer‐ip‐address: true
redis:
  keys:
    push_items: 'push:items'