server:
  port: 8686
spring:
  rabbitmq:
    host: 192.168.230.130

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/