server:
  port: 9005

spring:
  application:
    name: dearoffer-message

  rabbitmq:
    host: 192.168.230.128

tencent:
  message:
    appid: 1400204427
    appkey: 741378178a6fcdb1065e4818e0a21038
    smsSign: JavaKK
    register:
      templateId: 317057
      effectiveTime: 2

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8686/eureka
  instance:
    prefer‐ip‐address: true