server:
  port: 9005

spring:
  application:
    name: dearoffer-post
  data:
    mongodb:
      database: commentdb
      host: 192.168.230.130
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.230.130:3306/offer?characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 192.168.230.130

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  rabbitmq:
    host: 192.168.230.130


eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8686/eureka
  instance:
    prefer‐ip‐address: true

redis:
  keys:
    salary_credibility_fix: 136