server:
  port: 9006


  
spring:
  application:
    name: dearoffer-resume
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://45.40.205.130:3306/offer?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  rabbitmq:
    host: 129.28.154.216
eureka:
  client:
    service‐url:
#       defaultZone: http://129.28.154.216:8686/eureka
      defaultZone: http://localhost:8686/eureka
  instance:
    prefer‐ip‐address: true
