server:
  port: 9007

rabbitmq:
  host: 192.168.230.130

spring:
  application:
    name: dearoffer-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.230.130:9300

const:
  index-search:
    pageSize: 5

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8686/eureka
  instance:
    prefer‐ip‐address: true

rabbitmq:
  host: 192.168.230.130