server:
  port: 9999

spring:
  application:
    name: dearoffer-zuul
  rabbitmq:
    host: 129.28.154.216 
eureka:
  client:
    serviceUrl:
      defaultZone: http://129.28.154.216:8686/eureka/
  instance:
    prefer‐ip‐address: true

zuul:
  routes:
    dearoffer-auth:
      path: /auth/**
      serviceId: dearoffer-auth
    dearoffer-base:
      path: /base/**
      serviceId: dearoffer-base
    dearoffer-company:
      path: /company/**
      serviceId: dearoffer-company
    dearoffer-employment:
      path: /employ/**
      serviceId: dearoffer-employ
    dearoffer-post:
      path: /post/**
      serviceId: dearoffer-post
    dearoffer-resume:
      path: /resume/**
      serviceId: dearoffer-resume
    dearoffer-search:
      path: /search/**
      serviceId: dearoffer-search